### ISSUE TITLE
Question : Support for Gray Out (dim) Option

### ISSUE THREAD

**Issue by sganz** [linkedin/hopscotch#256] opened 2015-12-02 04:41 UTC
Not sure where to ask, hope it's ok to ask here -

I have seen a few other of the hopscotch-like packages do something when they select the element that the bubble is pointing to they dim out the rest of the page except for that div.

The question is does the v0.2.5 version have any support for that built in? If not v0.3 have an easy way to do it?

Thanks

Sandy

**Comment by zimmi88** [comment] 2016-06-15 22:41
Closing as duplicate of #16. I've put this on the roadmap as something we certainly want to do, though. =)

**Closed by zimmi88** 2016-06-15 22:41 UTC
