### ISSUE TITLE
How to use document.querySelectorAll within the target

### ISSUE THREAD

**Issue by hsiddique** [linkedin/hopscotch#301] opened 2016-09-21 16:06 UTC
Hi,

I have a webpage that is created dynamically.
Part of the  html code looks this

`<div class="toolbar-tab-container bound-visible">

   <ul class="toolbar-tab-control">

      <li class="toolbar-tab tb-tab-active"> <button title="">Tools</button> </li>

      <li class="toolbar-tab"> <button title="">Draw and Measure</button> </li>

      <li class="toolbar-tab"> <button title="">Custom Tools</button> </li>

   </ul>

</div>`

I want to create a step for each toolbar tab and was hoping to use the following
`
element: document.querySelectorAll('[class="toolbar-tab"]')[0],

element: document.querySelectorAll('[class="toolbar-tab"]')[1],

element: document.querySelectorAll('[class="toolbar-tab"]')[2],

`
but a popup does not appear , 
There are also some elements, that I want to find using the "title".

what is the correct way where I can use querySelectorAll to specify the correct element that I want to use?

thanks

**Comment by zimmi88** [comment] 2016-09-22 20:59
Given the above HTML, `document.querySelectorAll('[class="toolbar-tab"]')` will only match two elements... the first element isn't a match because of the additional class. Still, I'd expect that at least two bubbles would appear, though they'd point at the wrong elements for their step.

Consider using `document.querySelectorAll('.className')` instead. Other than that, I don't see a particular issue with the syntax above. I'd also recommend making sure the DOM structure exists on the page before you query for those elements using `document.querySelectorAll()`.

Closing because this doesn't appear to be an issue with the Hopscotch library. If, after the above suggested edit, the library is throwing errors or there's unexpected behavior that appears to be due to Hopscotch, please feel free to add a reply and I'll take a look.

**Closed by zimmi88** 2016-09-22 20:59 UTC
Labels: question
