### ISSUE TITLE
jQuery selector example

### ISSUE THREAD

**Issue by bsides** [linkedin/hopscotch#13] opened 2013-07-30 19:47 UTC
I believe it'd be very nice to have a jQuery selector example for target. After a lot of time testing, the final one I used was just the string "table tr:first-child td", but I didn't find it in the documentation.

Also, since this script's main use if for a tutorial after an event happened, it'd be nice i it was possible to bind it to an event.

Thank you.

**Comment by satish11nov** [comment] 2015-07-24 07:14
@bsides , any idea on how to use query selector for custom attributes (viewid)
<div viewid="94116fe4-633b-4422-8b6a-f7d24bee610d">

**Comment by bsides** [comment] 2015-07-24 08:19
That's more specific to jQuery, @satish11nov but answering:

```javascript
$('div[viewid]')
```

**Comment by satish11nov** [comment] 2015-07-24 08:46
ok so in my case it would be something like..
$('div[viewid]='94116fe4-633b-4422-8b6a-f7d24bee610d'')

**Comment by bsides** [comment] 2015-07-24 16:49
I suggest you to ask that in Stack Exchange or jQuery forums, but again answering, I believe the correct way to do that specifically for this one is `$('div[viewid=94116fe4-633b-4422-8b6a-f7d24bee610d')` or with quotes `$('div[viewid="94116fe4-633b-4422-8b6a-f7d24bee610d"]')`

**Comment by satish11nov** [comment] 2015-07-25 06:27
you are right. I have already figured out that syntax. Thanks a lot @bsides

**Comment by zimmi88** [comment] 2016-06-24 00:49
Closing as duplicate of #105.

**Closed by zimmi88** 2016-06-24 00:49 UTC
Labels: docs
