### ISSUE TITLE
Restarting tour from beginning on page reload

### ISSUE THREAD

**Issue by jessp** [linkedin/hopscotch#179] opened 2015-05-18 22:06 UTC
I'm having difficulty getting the tour to restart at the first step after page reload.

I've tried specifying a step in the `startTour()` function, and I've tried using `showStep()` passing in the first step in as an argument. Neither of these have worked (nor have they thrown an error).

As far as I know, there's no easy way to disable sharing data between sessions.

Could you point me in the right direction?

**Comment by jessp** [comment] 2015-05-19 18:38
As an update, I was able to work around this issue by having the tutorial start following a button press and then calling `hopscotch.startTour(tour, 0);`. However, I'm sure some users might prefer to have a tour simply start immediately without requiring interaction from the user or another workaround.

**Comment by zimmi88** [comment] 2015-05-19 22:14
Hi @jessp,

Do you have a code sample that duplicates this behavior? It sounds like this could be a known bug (attempting to call `startTour` before the DOM is ready could cause `hopscotch.startTour()` to forget the step that's passed in, falling back to sessionStorage/cookie instead) that we're currently investigating.

Thanks!

**Comment by jessp** [comment] 2015-05-19 22:39
@zimmi88,

Yes, that seems to be exactly the issue. I was calling `hopscotch.startTour(tour, 0);` without waiting for DOM readiness. My scripts aren't in the head, and DOM readiness didn't seem to impact the pop-up position/ability for the hopscotch script to run successfully, so I didn't make the connection. Is there any way to outright disable session/cookie storage without mucking with the source code? I don't mind waiting for DOM ready but part of me would just prefer to disable what (for me) are unnecessary processes. Thanks for your help!

**Comment by zimmi88** [comment] 2015-06-16 22:30
Great, thanks for the info! This sounds like a duplicate of #130, so I'll close this issue.

**Closed by zimmi88** 2015-06-16 22:30 UTC
Labels: needs-more-details

**Comment by shantilal-narola** [comment] 2018-11-13 07:14
I'm facing a similar issue, is there any way to resolve this? Passing `stepNum` to `startTour()` still doesn't restarts the tour.

**Comment by sneakyfildy** [comment] 2018-11-13 07:34
> I'm facing a similar issue, is there any way to resolve this? Passing `stepNum` to `startTour()` still doesn't restarts the tour.

Try to call hopscotch.endTour(true) this will clear a cookie, and then just hopscotch.startTour(yourTour)

**Comment by TIMEDOCK** [comment] 2019-01-31 04:55
Calling `hopscotch.endTour(true);`, before `hopscotch.startTour();`, as a way to restart the tour from the beginning, exposes a bug where the bubble's events (i.e. cancel button/link) will not be created for the new tour.

I discovered that in the `this.endTour` method, the line `currTour = null;` was never being called. To fix this issue, I moved it above the call to `destroyBubble();`
