### ISSUE TITLE
Close button not visible even after setting showCloseButton: true,

### ISSUE THREAD

**Issue by amitaltizon** [linkedin/hopscotch#152] opened 2015-04-09 05:24 UTC
Unable to see close button at the corner.

Though button is there in dom element, and it closes after clicking at top right corner.

**Comment by zimmi88** [comment] 2015-04-10 01:20
Hi @amitaltizon,

Sorry, I'm not able to reproduce this on my local copy (I'm using the `demo/index.html` page included with the Hopscotch distribution). Do you have any additional details and/or a code snippet that reproduces this behavior?

The close button is part of a sprite image file included with Hopscotch. It could be that this sprite file isn't present or there's some other CSS styles on the page that's clashing with the styles included by Hopscotch.

**Comment by zimmi88** [comment] 2015-04-21 23:58
Closing this issue for now. If there are additional details that can help us reproduce this issue, let us know and we can revisit. Thanks!

**Closed by zimmi88** 2015-04-21 23:58 UTC
Labels: needs-more-details

**Comment by amitaltizon** [comment] 2015-04-22 04:29
It was image issue.

I directly used hopscotch-rails gem. Images need to be kept at particular directory. 

Issue resolved.

Thanks
