### ISSUE TITLE
Adding Links and <li> to content

### ISSUE THREAD

**Issue by diondkb** [linkedin/hopscotch#196] opened 2015-06-30 13:46 UTC
Hi,

How do I display links and lists in the content are of the hopskotch bubble. I believe I need to use innerHTML. Would I check via one of the events when the tour advances, if it is the step I am looking for, then insert the links, lists etc by using javascript to find the containing element and then use innerHTML on that?

Thanks
Dion

**Comment by zimmi88** [comment] 2015-07-14 22:26
Hi @diondkb,

You should be able to include HTML as part of a tour/callout bubble's content. Try including the markup for your list as part of the step's `content` option... if this isn't working, let us know so we can investigate further.

**Comment by diondkb** [comment] 2015-07-15 03:24
Hi zimmi86,

Thanks for the reply and your time, but figured that out some time back. What I am now having trouble with is getting the link I put in the bubble to display a video in a html5 and jquery light box(like this one https://html5box.com/html5lightbox/index.php). It defaults to opening the video in a browser page? This should work out of the box, or am I mising something? JQuery and the necessary htmllightbox.js are loaded in wordpress. 

Cheers,
Dion

**Comment by zimmi88** [comment] 2015-07-15 07:35
This is likely because the DOM element doesn't exist on the page when the lightbox script is instantiated (assuming you're loading the lightbox script as part of the page's HTML). The bubble's content doesn't get created until it's needed, so when the lightbox script binds its click handler to the page on DOM ready, this link won't exist and thus the click event won't be captured by the lightbox library.

Hopscotch does provide an `onShow` callback that can be defined on a per-step or per-tour basis. When that callback is invoked, the bubble's content will exist on the page, so binding the click handler to the link at that point should work. Unfortunately, the documentation linked to above doesn't provide any API details for how to bind a new link to the lightbox script on the fly and debugging non-Hopscotch code would fall out of the scope of this issue tracker. Maaaaaaaybe you could try something like this...

````javascript
onShow: function(){
  // This mimics what the script does on DOM ready, but it's specifically
  // scoped to the new link only.
  $('.my-new-bubble-link').html5lightbox();
}
````

...and that might work, but I'm not sure if that'll end up leading to conflicting instances. You'd need to test this against your particular use case to make sure this works as intended.

I hope this helps! Since this issue appears related to another JS library, I'm going to close this issue, though if there are any additional concerns or the above info is unclear, feel free to respond and lemme know.

**Closed by zimmi88** 2015-07-15 07:35 UTC
Labels: needs-more-details

**Comment by diondkb** [comment] 2015-07-15 18:19
Thanks zimmi,

It worked!
