### ISSUE TITLE
Placement does not account for negative margin

### ISSUE THREAD

**Issue by cbojar** [linkedin/hopscotch#135] opened 2014-11-26 16:56 UTC
I have a header with a negative margin that pulls up the main area below that. Inside of that is where the Hopscotch tour happens. The bubbles all are off by the amount of the negative margin. Happens in both latest FF and Chrome.

Right now, my workaround is to set `step.yOffset = <negative margin>` and it pulls it up to the correct spot. I'm not really sure if anything can be done about this, but just wanted to let you know about the issue.

Thanks.

**Comment by zimmi88** [comment] 2015-02-07 02:45
Hi @cbojar,

Thanks for the info! I tried reproducing this issue but was unable to cause the behavior described above.

Testing details:
- Hopscotch v.0.2.3
- Chrome latest, Firefox latest
- Test code - https://gist.github.com/zimmi88/a44c44c4a08553a64ab0. The files in this gist were all included in an `/issuetest` folder in my hopscotch repo.

Might be missing something in my test, though. Any additional details I can use to reproduce this issue?

**Comment by cbojar** [comment] 2015-02-09 17:40
Thanks for your reply @zimmi88. I tried to reproduce the issue with the test code, and I think I see what the problem is. By default, hopscotch aligns the top of the bubble with the top of the element it is referencing. My elements were short, so the arrow pointed below them. This is just the way hopscotch seems to work by default. I needed a -20px y-offset, which I see you also use in your demo, so I suppose this is not uncommon. The fact that it seemed to match the negative margin was coincidence.

So I took a look at the documentation and saw that `yOffset` can be set to `"center"` to simply center the bubble on the element. Unfortunately, with that set, the bubble appears way above the element it is referencing, and this is even true when there are no special styles  set. It seems to vertically center the bubble box, but not the arrow, on the element. I see that the arrow can also be centered. This behavior is not totally intuitive to me, though it may be the intended behavior.

I guess in the end, this is not a bug but a quirk of the software that I need to account for.

**Comment by zimmi88** [comment] 2015-02-21 02:55
Thanks for the info. Since it sounds like Hopscotch is working as expected, I'm going to go ahead and close this issue. I think the quirk you mentioned regarding `yOffset: center` not necessarily implying `arrowOffset: center` might be something worth exploring. I forget if there's a good reason why this wouldn't be the case, but nonetheless I'll open up a new thread to explore the topic.

**Closed by zimmi88** 2015-02-21 02:55 UTC
Labels: needs-more-details
