### ISSUE TITLE
Auto Scrolling doesn't work for Divs which is larger than Screen Resolution

### ISSUE THREAD

**Issue by NaveenKumarGNK** [linkedin/hopscotch#265] opened 2016-02-23 09:53 UTC
@kate2753  @kishoreg @chriseppstein @nanek @yeah @joehalliwell  Have a Problem in Scrolling.,

I am trying to provide tour for a page containing single div.consider it contains eight references id to show.if three target ids are visible without scroll but the fourth id is not visible for that its not scrolling to visible that div as you shown in demo.Even if i scroll manually means it doesnt point the next target correctly.it moves someways based on the height we scrolled.It doesnt point to the next div perfectly.

**Comment by shivasingh0101** [comment] 2016-06-06 09:33
The same situation here.can anyone provide a solution ??

**Comment by zimmi88** [comment] 2016-06-15 23:43
Hmm... if I recall correctly, Hopscotch is going to try to scroll to the top of the div, which depending on the placement of the bubble might mean the bubble isn't shown. This edge case might already be tracked in another ticket. For now, I'll mark as a bug, though I don't anticipate being able to work on this for the immediate future, I'm afraid.

**Comment by zimmi88** [comment] 2016-06-15 23:52
Yep, this is a duplicate of #214, so closing.

**Closed by zimmi88** 2016-06-15 23:52 UTC
Labels: bug
